CMS-719: README file
pantheon-systems/wordpress-bedrock-integrations pull request #1
Opened 2022-06-10 20:10 UTC by rwagner00

2022-06-10 20:34 UTC, jspellman814 requested changes

2022-06-10 20:34 UTC, jspellman814 commented on README.md
> +This repo contains settings, configuration, and functionality to enable a WordPress site to work on Pantheon.
We should clarify the upstream this is intended to be used with (`wordpress-bedrock-recommended`), and that it is [included in the upstream](https://github.com/pantheon-systems/wordpress-bedrock-recommended/blob/master/composer.json#L25)  by default.

And maybe we call out how this repo is being used within `wordpress-bedrock-recommended` (e.g. This repo is pulled into Pantheon's WordPress Bedrock Recommended upstream, and its contents are placed into the necessary places via the [cleanup-composer script](https://github.com/pantheon-systems/wordpress-bedrock-recommended/blob/master/scripts/composer/cleanup-composer#L13)). We should also document the cleanup-composer script in the upstream, but adding a note about it here should give folks some context as to what purpose this repo serves.

2022-06-10 20:34 UTC, jspellman814 commented on README.md
> +Add this to a project via composer: `composer require pantheon-systems/wordpress-bedrock-integrations`.
Not certain about including this line, as installing this repo as is doesn't actually do anything.

2022-06-13 22:29 UTC, rwagner00 commented
@jspellman814 Updated!

2022-06-13 22:48 UTC, jspellman814 commented on README.md
> +This repo contains settings, configuration, and functionality to enable a WordPress site to work on Pantheon. It is included by default in the Pantheon standard WordPress upstream, and its contents a
```suggestion
This repo contains settings, configuration, and functionality to enable a WordPress site to work on Pantheon. It is included by default in Pantheon's [Composer-enabled WordPress upstream](https://github.com/pantheon-systems/wordpress-bedrock-recommended), and its contents are placed into their correct locations via the [cleanup-composer script](https://github.com/pantheon-systems/wordpress-bedrock-recommended/blob/master/scripts/composer/cleanup-composer). 
```

2022-06-13 22:48 UTC, jspellman814 commented
One small change, but otherwise looks good to me!

2022-06-16 19:27 UTC, merged